"""组装千里单骑 Flow 树（结构在此一览；mod / relocate 分文件）。"""

from __future__ import annotations

from vision_bot.apps.ming_jiang_sha.actions import go_back
from vision_bot.apps.ming_jiang_sha.qian_li_dan_qi.flows import (
    ba_qing_store,
    battle_hub,
    enter_pick,
    fei_fei,
    fight,
    home_recovery,
    mo_zi,
    pick_battle,
    pick_event,
    pick_shop,
    pocket_event,
    qian_li,
    rest,
    run_ended,
    shi_chang_shi,
    zhu_ge_liang,
)
from vision_bot.runtime.builders import flow, mod
from vision_bot.runtime.flow import Flow


def build_qian_li_dan_qi() -> Flow:
    return flow(
        id="qldq",
        name="千里单骑",
        params={"wu_jiang": "吕布"},
        relocate=qian_li.relocate,
        children=[
            flow(
                id="qldq.battle_select.enter_pick",
                name="选将",
                params={"wu_jiang": "吕布"},
                relocate=enter_pick.relocate,
                children=[
                    mod(
                        id="qldq.battle_select.enter_pick.select_wu_jiang",
                        name="选武将",
                        active=enter_pick.select_wu_jiang,
                    ),
                    mod(
                        id="qldq.battle_select.enter_pick.focus_search",
                        name="聚焦搜索",
                        active=enter_pick.focus_search,
                    ),
                    mod(
                        id="qldq.battle_select.enter_pick.type_name",
                        name="输入武将",
                        active=enter_pick.type_name,
                    ),
                    mod(
                        id="qldq.battle_select.enter_pick.click_search",
                        name="搜索",
                        active=enter_pick.click_search,
                    ),
                    mod(
                        id="qldq.battle_select.enter_pick.click_general",
                        name="选武将",
                        active=enter_pick.click_general,
                    ),
                    mod(
                        id="qldq.battle_select.enter_pick.go_back",
                        name="返回",
                        active=go_back,
                    ),
                    mod(
                        id="qldq.battle_select.enter_pick.click_start",
                        name="点击开始",
                        active=enter_pick.click_start,
                    ),
                ],
            ),
            flow(
                id="qldq.battle_interface",
                name="战斗界面",
                children=[
                    flow(
                        id="qldq.battle_hub",
                        name="三选一枢纽",
                        relocate=battle_hub.relocate,
                        children=[
                            mod(
                                id="qldq.battle_hub.dismiss_up",
                                name="关闭上面板",
                                active=battle_hub.dismiss_up,
                            ),
                            flow(
                                id="qldq.battle_hub.pick_battle",
                                name="战斗三选一",
                                relocate=pick_battle.relocate,
                                children=[
                                    mod(
                                        id="qldq.battle_hub.pick_battle.choose",
                                        name="选战斗",
                                        active=pick_battle.choose,
                                    ),
                                    mod(
                                        id="qldq.battle_hub.pick_battle.choose_yi_wai",
                                        name="选意外",
                                        active=pick_battle.choose_yi_wai,
                                    ),
                                    mod(
                                        id="qldq.battle_hub.pick_battle.pre_confirm",
                                        name="确认",
                                        active=pick_battle.pre_confirm,
                                    ),
                                ],
                            ),
                            flow(
                                id="qldq.battle_hub.pick_shop",
                                name="商店三选一",
                                relocate=pick_shop.relocate,
                                children=[
                                    mod(
                                        id="qldq.battle_hub.pick_shop.choose",
                                        name="选商店",
                                        active=pick_shop.choose,
                                    ),
                                ],
                            ),
                            flow(
                                id="qldq.battle_hub.pick_event",
                                name="事件三选一",
                                relocate=pick_event.relocate,
                                children=[
                                    mod(
                                        id="qldq.battle_hub.pick_event.choose",
                                        name="选事件",
                                        active=pick_event.choose,
                                    ),
                                    mod(
                                        id="qldq.battle_hub.pick_event.confirm",
                                        name="确认",
                                        active=pick_event.confirm,
                                    ),
                                ],
                            ),
                        ],
                    ),
                    flow(
                        id="qldq.fight",
                        name="战斗",
                        # relocate=fight.relocate,
                        children=[
                            mod(
                                id="qldq.fight.move_aside",
                                name="移开鼠标",
                                active=fight.move_aside,
                            ),
                            mod(
                                id="qldq.fight.click_cancel",
                                name="点取消",
                                active=fight.click_cancel,
                            ),
                            mod(
                                id="qldq.fight.click_setting",
                                name="点设置",
                                active=fight.click_setting,
                            ),
                            mod(
                                id="qldq.fight.click_auto",
                                name="点自动",
                                active=fight.click_auto,
                            ),
                            mod(
                                id="qldq.fight.wait_end",
                                name="等结束",
                                active=fight.wait_end,
                            ),
                            mod(
                                id="qldq.fight.next_step",
                                name="下一步",
                                active=fight.next_step,
                            ),
                            mod(
                                id="qldq.fight.check_run_end",
                                name="本轮结束判定",
                                active=fight.check_run_end,
                            ),
                            mod(
                                id="qldq.fight.after_settle",
                                name="结算分支",
                                active=fight.after_settle,
                            ),
                            mod(
                                id="qldq.fight.choose_reward_title",
                                name="选择赠礼武将",
                                active=fight.choose_reward_title,
                            ),
                            mod(
                                id="qldq.fight.choose_reward_kind",
                                name="选择赠礼类别",
                                active=fight.choose_reward_kind,
                            ),
                        ],
                    ),
                    flow(
                        id="qldq.ba_qing_store",
                        name="巴清商店",
                        relocate=ba_qing_store.relocate,
                        children=[
                            mod(
                                id="qldq.ba_qing_store.click_token_slot",
                                name="购买信物背包格子",
                                active=ba_qing_store.click_token_slot,
                            ),
                            mod(
                                id="qldq.ba_qing_store.slot_confirm",
                                name="确认买格子",
                                active=ba_qing_store.slot_confirm,
                            ),
                            mod(
                                id="qldq.ba_qing_store.slot_no_buy",
                                name="格子钱不够关窗",
                                active=ba_qing_store.slot_no_buy,
                            ),
                            mod(
                                id="qldq.ba_qing_store.choose_token",
                                name="购买信物",
                                active=ba_qing_store.choose_token,
                            ),
                            mod(
                                id="qldq.ba_qing_store.token_confirm",
                                name="确认买信物",
                                active=ba_qing_store.token_confirm,
                            ),
                            mod(
                                id="qldq.ba_qing_store.token_no_buy",
                                name="信物钱不够关窗",
                                active=ba_qing_store.token_no_buy,
                            ),
                            mod(
                                id="qldq.ba_qing_store.go_back",
                                name="返回",
                                active=ba_qing_store.go_back,
                            ),
                            mod(
                                id="qldq.ba_qing_store.confirm",
                                name="确认",
                                active=ba_qing_store.confirm,
                            ),
                        ],
                    ),
                    flow(
                        id="qldq.pocket_event",
                        name="锦囊",
                        children=[
                            mod(
                                id="qldq.pocket_event.enter",
                                name="进店选锦囊",
                                active=pocket_event.enter,
                            ),
                            mod(
                                id="qldq.pocket_event.check",
                                name="检查",
                                active=pocket_event.check,
                            ),
                        ],
                    ),
                    flow(
                        id="qldq.rest",
                        name="休息",
                        children=[
                            mod(
                                id="qldq.rest.click_slot",
                                name="点休息",
                                active=rest.click_slot,
                            ),
                        ],
                    ),
                    flow(
                        id="qldq.fei_fei",
                        name="妃妃",
                        children=[
                            mod(
                                id="qldq.fei_fei.choose",
                                name="选择",
                                active=fei_fei.choose,
                            ),
                        ],
                    ),
                    flow(
                        id="qldq.mo_zi",
                        name="墨子",
                        children=[
                            mod(
                                id="qldq.mo_zi.click",
                                name="点选项",
                                active=mo_zi.click_option,
                            ),
                        ],
                    ),
                    flow(
                        id="qldq.zhu_ge_liang",
                        name="诸葛亮",
                        children=[
                            mod(
                                id="qldq.zhu_ge_liang.wait_title",
                                name="等标题",
                                active=zhu_ge_liang.wait_title,
                            ),
                            mod(
                                id="qldq.zhu_ge_liang.click_next",
                                name="点继续",
                                active=zhu_ge_liang.click_next,
                            ),
                        ],
                    ),
                    flow(
                        id="qldq.shi_chang_shi",
                        name="十常侍",
                        relocate=shi_chang_shi.relocate,
                        children=[
                            mod(
                                id="qldq.shi_chang_shi.attack",
                                name="攻击",
                                active=shi_chang_shi.attack,
                            ),
                            mod(
                                id="qldq.shi_chang_shi.check_cancel",
                                name="检查取消",
                                active=shi_chang_shi.check_cancel,
                            ),
                        ],
                    ),
                    flow(
                        id="qldq.run_ended",
                        name="本轮结束",
                        children=[
                            mod(
                                id="qldq.run_ended.confirm",
                                name="确认",
                                active=run_ended.confirm,
                            ),
                            mod(
                                id="qldq.run_ended.close",
                                name="关闭",
                                active=run_ended.close,
                            ),
                        ],
                    ),
                ],
            ),
            # 仅失败/卡死时 goto/call；正常路径靠根 relocate
            flow(
                id="qldq.home_recovery",
                name="回首页恢复",
                relocate=home_recovery.relocate,
                children=[
                    mod(
                        id="qldq.home_recovery.esc_home",
                        name="Esc回首页",
                        active=home_recovery.esc_home,
                    ),
                ],
            ),
        ],
    )
